<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    <img class="icon" src="/resources/icon/ade.png" data-icon="ade">
        <img class="icon" src="/resources/icon/ade2.png" data-icon="ade2">
        <img class="icon" src="/resources/icon/beer.png" data-icon="beer">
        <img class="icon" src="/resources/icon/beer2.png" data-icon="beer2">
        <img class="icon" src="/resources/icon/bread.png" data-icon="bread">
        <img class="icon" src="/resources/icon/bread2.png" data-icon="bread2">
        <img class="icon" src="/resources/icon/burger.png" data-icon="burger">
        <img class="icon" src="/resources/icon/burger2.png" data-icon="burger2">
        <img class="icon" src="/resources/icon/burgerset.png" data-icon="burgerset">
        <img class="icon" src="/resources/icon/burgerset2.png" data-icon="burgerset2">
        <img class="icon" src="/resources/icon/cake.png" data-icon="cake">
        <img class="icon" src="/resources/icon/cake2.png" data-icon="cake2">
        <img class="icon" src="/resources/icon/cheese.png" data-icon="cheese">
        <img class="icon" src="/resources/icon/cheese2.png" data-icon="cheese2">
        <img class="icon" src="/resources/icon/chicken.png" data-icon="chicken">
        <img class="icon" src="/resources/icon/chicken2.png" data-icon="chicken2">
        <img class="icon" src="/resources/icon/coffee.png" data-icon="coffee">
        <img class="icon" src="/resources/icon/coffee2.png" data-icon="coffee2">
        <img class="icon" src="/resources/icon/frenchfries.png" data-icon="frenchfries">
        <img class="icon" src="/resources/icon/frenchfries2.png" data-icon="frenchfries2">
        <img class="icon" src="/resources/icon/friedrice.png" data-icon="friedrice">
        <img class="icon" src="/resources/icon/friedrice2.png" data-icon="friedrice2">
        <img class="icon" src="/resources/icon/gimbab.png" data-icon="gimbab">
        <img class="icon" src="/resources/icon/gimbab2.png" data-icon="gimbab2">
        <img class="icon" src="/resources/icon/jajangmyeon.png" data-icon="jajangmyeon">
        <img class="icon" src="/resources/icon/jajangmyeon2.png" data-icon="jajangmyeon2">
        <img class="icon" src="/resources/icon/noodles.png" data-icon="noodles">
        <img class="icon" src="/resources/icon/noodles2.png" data-icon="noodles2">
        <img class="icon" src="/resources/icon/pasta.png" data-icon="pasta">
        <img class="icon" src="/resources/icon/pasta2.png" data-icon="pasta2">
        <img class="icon" src="/resources/icon/pizza.png" data-icon="pizza">
        <img class="icon" src="/resources/icon/pizza2.png" data-icon="pizza2">
        <img class="icon" src="/resources/icon/ramen.png" data-icon="ramen">
        <img class="icon" src="/resources/icon/ramen2.png" data-icon="ramen2">
        <img class="icon" src="/resources/icon/rice.png" data-icon="rice">
        <img class="icon" src="/resources/icon/rice2.png" data-icon="rice2">
        <img class="icon" src="/resources/icon/salad.png" data-icon="salad">
        <img class="icon" src="/resources/icon/salad2.png" data-icon="salad2">
        <img class="icon" src="/resources/icon/samgyeobsal.png" data-icon="samgyeobsal">
        <img class="icon" src="/resources/icon/samgyeobsal2.png" data-icon="samgyeobsal2">
        <img class="icon" src="/resources/icon/sandwich.png" data-icon="sandwich">
        <img class="icon" src="/resources/icon/sandwich2.png" data-icon="sandwich2">
        <img class="icon" src="/resources/icon/soju.png" data-icon="soju">
        <img class="icon" src="/resources/icon/soju2.png" data-icon="soju2">
        <img class="icon" src="/resources/icon/steak.png" data-icon="steak">
        <img class="icon" src="/resources/icon/steak2.png" data-icon="steak2">
        <img class="icon" src="/resources/icon/sushi.png" data-icon="sushi">
        <img class="icon" src="/resources/icon/sushi2.png" data-icon="sushi2">
        <img class="icon" src="/resources/icon/tteokbokki.png" data-icon="tteokbokki">
        <img class="icon" src="/resources/icon/tteokbokki2.png" data-icon="tteokbokki2">
 
 